### ISSUE TITLE
Filter OpenTelemetry events

### ISSUE THREAD

**Issue by agross** [JasperFx/wolverine#451]
This is a screenshot of the Jaeger UI after starting the app with a previously empty Jaeger database.

![image](https://github.com/JasperFx/wolverine/assets/16245/eb169aab-57c5-4322-b5f0-80dcb22b3f68)

After a couple of minutes the outlier to the left contains around 150 spans related to background operations. I could get rid of them by filtering spans with the opentelemetry-collector:

```yaml
processors:
  filter/wolverine-internal:
    traces:
      span:
        - 'IsMatch(attributes["messaging.message_type"], "^Wolverine\\.RDBMS\\..*")'
        - 'IsMatch(attributes["messaging.message_type"], "^Wolverine\\.Runtime\\.Agents\\..*")'
        - 'IsMatch(attributes["db.statement"], "wolverine_messages")' # These are Npgsql statements issued by the background job.
```

Perhaps it's not necessary to log those spans in the first place.
